import type { Listing } from './types'

export const seedListings: Listing[] = [
  {
    id: 'seed-1',
    title: '20ft Utility Trailer',
    description: 'Heavy-duty steel utility trailer with loading ramps. Great for hauling ATVs, landscaping equipment, and general cargo. Ball hitch 2-5/16". Lights in good working order.',
    category: 'trailer',
    condition: 'good',
    pricePerDay: 75,
    location: 'Bozeman, MT',
    contactName: 'Dave R.',
    contactPhone: '(406) 555-0182',
    contactEmail: 'dave@example.com',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    available: true,
  },
  {
    id: 'seed-2',
    title: 'Car Hauler Trailer — 18ft',
    description: 'Open car hauler with hydraulic tilt deck. Holds up to 10,000 lbs. Perfect for moving vehicles, tractors, or heavy equipment. Requires 3/4 ton pickup or larger.',
    category: 'trailer',
    condition: 'excellent',
    pricePerDay: 120,
    location: 'Billings, MT',
    contactName: 'Mark T.',
    contactPhone: '(406) 555-0234',
    contactEmail: 'markt@example.com',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&q=80',
    available: true,
  },
  {
    id: 'seed-3',
    title: 'Dump Trailer — 14ft',
    description: '14ft dump trailer with 14,000 lb GVWR. Hydraulic dump, spreader gate, and tarp. Great for mulch, gravel, or demolition debris. Full day or weekend rates available.',
    category: 'trailer',
    condition: 'good',
    pricePerDay: 95,
    location: 'Missoula, MT',
    contactName: 'Sarah K.',
    contactPhone: '(406) 555-0310',
    contactEmail: 'sarahk@example.com',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1581094288338-2314dddb7ece?w=800&q=80',
    available: true,
  },
  {
    id: 'seed-4',
    title: 'Mini Excavator — Kubota KX040',
    description: '4-ton mini excavator with 12" and 24" buckets included. Excellent digging depth of 11ft. Recently serviced. Perfect for trenching, landscape grading, and foundation work. Delivery available.',
    category: 'backhoe',
    condition: 'excellent',
    pricePerDay: 350,
    location: 'Bozeman, MT',
    contactName: 'Jim L.',
    contactPhone: '(406) 555-0401',
    contactEmail: 'jiml@example.com',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
    available: true,
  },
  {
    id: 'seed-5',
    title: 'Skid Steer — Bobcat S570',
    description: 'Bobcat S570 skid steer with bucket and pallet forks. 70 hp, 2,200 lb rated operating capacity. Great for moving materials, grading, or snow removal. Must show proof of experience.',
    category: 'backhoe',
    condition: 'good',
    pricePerDay: 275,
    location: 'Helena, MT',
    contactName: 'Tom W.',
    contactPhone: '(406) 555-0512',
    contactEmail: 'tomw@example.com',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1581094794329-c811a48c0c15?w=800&q=80',
    available: true,
  },
  {
    id: 'seed-6',
    title: 'Trencher — Ditch Witch RT45',
    description: 'Walk-behind trencher, digs 4" wide x 36" deep. Great for irrigation lines, conduit, or drainage. Easy to operate. Includes safety gear. Half-day rate also available.',
    category: 'backhoe',
    condition: 'fair',
    pricePerDay: 185,
    location: 'Great Falls, MT',
    contactName: 'Linda M.',
    contactPhone: '(406) 555-0623',
    contactEmail: 'lindam@example.com',
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d17?w=800&q=80',
    available: true,
  },
  {
    id: 'seed-7',
    title: 'Plate Compactor — 150 lb',
    description: 'Wacker Neuson plate compactor. Essential for compacting gravel bases, pavers, and asphalt patches. 150 lb, single-direction. Comes with water tank for asphalt compaction.',
    category: 'tool',
    condition: 'good',
    pricePerDay: 65,
    location: 'Bozeman, MT',
    contactName: 'Ryan S.',
    contactPhone: '(406) 555-0714',
    contactEmail: 'ryans@example.com',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1590496793929-36417d3117de?w=800&q=80',
    available: true,
  },
  {
    id: 'seed-8',
    title: 'Pressure Washer — 4200 PSI',
    description: 'Gas-powered pressure washer, 4200 PSI / 4 GPM. Includes surface cleaner, turbo nozzle, and 50ft hose. Great for driveways, decks, equipment, and siding. Mix of nozzle tips included.',
    category: 'tool',
    condition: 'excellent',
    pricePerDay: 55,
    location: 'Missoula, MT',
    contactName: 'Beth A.',
    contactPhone: '(406) 555-0821',
    contactEmail: 'betha@example.com',
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80',
    available: true,
  },
  {
    id: 'seed-9',
    title: 'Portable Generator — 10,000W',
    description: 'Generac 10,000W portable generator. Powers job sites, events, or emergency backup. Electric start, 120V/240V outlets, and low-oil shutoff. ~10 hour runtime at half load. Full tank of gas included.',
    category: 'tool',
    condition: 'good',
    pricePerDay: 80,
    location: 'Billings, MT',
    contactName: 'Chris N.',
    contactPhone: '(406) 555-0933',
    contactEmail: 'chrisn@example.com',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    available: false,
  },
  {
    id: 'seed-10',
    title: 'Wet Tile Saw — 10" Blade',
    description: 'MK Diamond 10" wet tile saw. Cuts ceramic, porcelain, natural stone, and pavers. Rolling table, mitre guide, and splash guard. Perfect for bath, kitchen, or outdoor tile projects.',
    category: 'tool',
    condition: 'good',
    pricePerDay: 45,
    location: 'Bozeman, MT',
    contactName: 'Amy J.',
    contactPhone: '(406) 555-1045',
    contactEmail: 'amyj@example.com',
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&q=80',
    available: true,
  },
]
